name: build
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - run: yarn
      - run: yarn run test
      - run: yarn run build:docs

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
